"""
constants.py — Static enumerations used for CLI tab-completion and validation.
"""

# ---------------------------------------------------------------------------
# All valid pipeline_tag values (sourced from huggingface.js/packages/tasks)
# ---------------------------------------------------------------------------

PIPELINE_TAGS = [
    # NLP
    "text-classification",
    "token-classification",
    "table-question-answering",
    "question-answering",
    "zero-shot-classification",
    "translation",
    "summarization",
    "feature-extraction",
    "text-generation",
    "fill-mask",
    "sentence-similarity",
    "text-ranking",
    "text-retrieval",
    # Audio
    "text-to-speech",
    "text-to-audio",
    "automatic-speech-recognition",
    "audio-to-audio",
    "audio-classification",
    "voice-activity-detection",
    "audio-text-to-text",
    # Computer Vision
    "depth-estimation",
    "image-classification",
    "object-detection",
    "image-segmentation",
    "text-to-image",
    "image-to-text",
    "image-to-image",
    "image-to-video",
    "unconditional-image-generation",
    "video-classification",
    "zero-shot-image-classification",
    "mask-generation",
    "zero-shot-object-detection",
    "text-to-3d",
    "image-to-3d",
    "image-feature-extraction",
    "text-to-video",
    "keypoint-detection",
    "video-to-video",
    # Multimodal
    "image-text-to-text",
    "image-text-to-image",
    "image-text-to-video",
    "visual-question-answering",
    "document-question-answering",
    "video-text-to-text",
    "visual-document-retrieval",
    "any-to-any",
    # Tabular / RL / Other
    "tabular-classification",
    "tabular-regression",
    "time-series-forecasting",
    "reinforcement-learning",
    "robotics",
    "graph-ml",
]

# ---------------------------------------------------------------------------
# Common model tags for tab-completion (not exhaustive — Hub has thousands)
# Categories: format, library, training-type, license, language
# ---------------------------------------------------------------------------

COMMON_TAGS = [
    # --- Formats / quantization ---
    "gguf",
    "safetensors",
    "gptq",
    "awq",
    "exl2",
    "bnb",
    # --- Libraries / frameworks ---
    "transformers",
    "pytorch",
    "tensorflow",
    "jax",
    "diffusers",
    "sentence-transformers",
    "peft",
    "trl",
    "timm",
    "spacy",
    "flair",
    "fastai",
    "scikit-learn",
    "xgboost",
    "lightgbm",
    "llama-cpp",
    "vllm",
    "ollama",
    "mlx",
    "mlx-lm",
    "ctransformers",
    # --- Inference / serving ---
    "text-generation-inference",
    # --- Training / fine-tune type ---
    "rlhf",
    "dpo",
    "instruction-tuned",
    "chat",
    "base-model",
    "fine-tuned",
    "merged",
    "lora",
    "qlora",
    # --- Licenses ---
    "apache-2.0",
    "mit",
    "cc-by-4.0",
    "cc-by-nc-4.0",
    "cc-by-sa-4.0",
    "cc-by-nc-sa-4.0",
    "cc0-1.0",
    "gpl-3.0",
    "lgpl-3.0",
    "llama3",
    "gemma",
    "openrail",
    "openrail++",
    "other",
    # --- Languages (ISO 639-1) ---
    "en",
    "fr",
    "de",
    "es",
    "it",
    "pt",
    "nl",
    "ru",
    "zh",
    "ja",
    "ko",
    "ar",
    "hi",
    "tr",
    "vi",
    "th",
    "id",
    "sv",
    "da",
    "no",
    "fi",
    "pl",
    "cs",
    "hu",
    "ro",
    "uk",
    "bg",
    "he",
    "fa",
    "ca",
    "hr",
]
